quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/rewardsdb

quarkus.datasource.jdbc.additional-jdbc-properties."TimeZone"=Asia/Kolkata

quarkus.hibernate-orm.schema-management.strategy=update